


cloud:
  aws:
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${SCRET_KEY}
    region:
      static: us-east-2
    stack:
      auto: false

application:
  bucket:
    name: gabrielmendonca-dados

spring:
  servlet:
    multipart:
      enabled: true  # "enabled" estava com nome errado
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB
  main:
    allow-bean-definition-overriding: true  # Adicionado para evitar erro "ConditionEvaluationReportLogger"
